USE [Praktyki]
GO

/****** Object:  Table [dbo].[Klasy]    Script Date: 16.12.2024 14:56:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Klasy](
	[KlasaID] [int] IDENTITY(1,1) NOT NULL,
	[NazwaKlasy] [nvarchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[KlasaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

